### ISSUE TITLE
Make an image based on alpine

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-ci-stack#1]
For the moment I tried the following Dockerfile
```docker
FROM node:6-alpine

# install Java
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
RUN apk add --no-cache openjdk8

# install yeoman
RUN npm install -g yo

# install bower
RUN npm install -g bower

#install gulp
RUN npm install -g gulp

#install yarn
RUN npm install -g yarn
```
which failed at PhantomJS tests

**Comment by PierreBesson** [comment]
I'm not sure it is worth it to base the CI image on alpine. We will get a lot of headaches trying to work around alpine specifics when we can just base the image on standard ubuntu.

**Comment by cbornet** [comment]
If we need to install stuff such as Chrome: yes, probably...
Otherwise, they are really smaller !

**Comment by cbornet** [comment]
So PhantomJS seems a PITA to setup on Alpine. So closing for now...
