### ISSUE TITLE
Configure Docker Service on Github

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-ci-stack#2]
I made the configuration on Docker Hub. Here the 1st tag: https://hub.docker.com/r/jhipster/jhipster-ci-stack/tags/

As usual, we need you @jdubois : can you configure the settings on github project plz?
- Go to settings > Integration & services > Add service
- Select Docker
- Click [x] active
- Click on 'Add service'

Thanks in advance.

**Comment by jdubois** [comment]
Thanks @pascalgrimaud for the instructions!
It's done.

**Comment by cbornet** [comment]
There is only a tag "master" but no "latest" so `docker pull jhipster/jhipster-ci-stack` fails.
Only `docker pull jhipster/jhipster-ci-stack:master` works

**Comment by pascalgrimaud** [comment]
@cbornet : yes it was intended, as usually, latest=last tag
Do you want I change it for development ?

Here the config I made on Docker Hub:
- branch master -> master
- tag -> latest
- tag -> same as tag name

**Comment by cbornet** [comment]
Yes, can you make a tag (0.1.0 ?) so that we have a latest ?

**Comment by pascalgrimaud** [comment]
I made a simple tag on Github: https://github.com/jhipster/jhipster-ci-stack/releases/tag/v0.0.1
On Docker Hub, there is 2 builds in queue (automatically). These images will be available in few minutes:
- jhipster/jhipster-ci-stack:v0.0.1
- jhipster/jhipster-ci-stack:latest (some minutes after the v0.0.1)

**Comment by cbornet** [comment]
Thanks.

**Comment by cbornet** [comment]
Works perfectly for me:
![pipeline](https://cloud.githubusercontent.com/assets/11633333/20927604/a26f43e4-bbc2-11e6-8c22-b32b54260bb5.png)

**Comment by atomfrede** [comment]
I can try it out on my gitlab demo projects later today.
